controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controller:
      type: forward_command_controller/ForwardCommandController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

position_controller:
  ros__parameters:
    joints:
      - hip_FL
      - ankle_FL
      - hip_BL
      - ankle_BL
      - hip_FR
      - ankle_FR
      - hip_BR
      - ankle_BR
    interface_name: position

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["drive_FL", "drive_BL"]
    right_wheel_names: ["drive_FR", "drive_BR"]
    
    wheel_separation: 0.23 # Approximate, tweak if necessary // 
    wheel_radius: 0.110 # Approximate, tweak if necessary // 110 mm ot -- 202 diameter // front to back  370mm

    use_stamped_vel: false

    # optional params to prevent sudden jerks
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 1.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 1.0
